### ISSUE TITLE
`Insufficient funds` error when trust line is not authorized

### ISSUE THREAD

**Issue by bartekn** [irisli/stellarterm#100]
Stellarterm displays "Insufficient funds" error when trust line is not authorized. Should be changed to something like "Insufficient funds or trust line not authorized" (I don't think it's possible to check via horizon).

**Comment by irisli** [comment]
Can you give me more details on where this exists? Thanks

**Comment by bartekn** [comment]
[Issuer](https://horizon-testnet.stellar.org/accounts/GCEB4DRBG6DGVITQ2FI6AFBDZHSATCHRRX4TQQDE5LDJ4FKX3FNLIHJY) has `auth_required` flag set. Login as another account:
```
GAPJKTLGS7FPKL6GSKMLYR2ZRMUNCYLQ6Z56VMRWOX72N2Z2GVNZVITN
SDLKFZQ6P6LBDXC7JHY3GOIBGCJTKSKDECQFQJTMA4LRDV2A7VYW2GD6
```
it has trustline but it has been revoked by the issuer. Try to create a trade in XLM - AAA.GCEB market. The error:
```
Failed to create offer. Possible reasons why:
* Not enough funds to complete order.
```
Should also contain: `Trust line not authorized.` You can actually find the real reason in Horizon error details.

**Comment by irisli** [comment]
Oh okay interesting. This is a really obscure issue though but it's good to know

**Comment by jedmccaleb** [comment]
It isn't that obscure. Lot's of issuers will have auth_required set

**Comment by irisli** [comment]
Hm okay, is there some existing thing on testnet I can test against?

**Comment by bartekn** [comment]
Check my comment above.

**Comment by Smartlands** [comment]
"*Not enough fund to complete order" is not a likely real reason because, in case of submission of an offer (through Stellar portal or Laboratory) with an amount that is more than available funds, the offer is created for all available funds. It is not possible to submit such an offer is StellarTerm (as it checks the balance and just deactivates the button to submit an offer). So actually it is not possible to run into a mistake when there are not enough funds to complete an offer (in terms of an asset that is meant to be sold). Moreover, mistake code "sell_not_authorized" should be easily identified.
    "result_codes": {
      "transaction": "tx_failed",
      "operations": [
        "sell_not_authorized"
      ]
    },
In case of creating an offer that results in a minimum required balance that exceeds current XLM balance, the result provided by Horizon is shown below ("op_low_reserve"). Stellarterm though does not provide any response (stucks at "Creating an offer...")
    "result_codes": {
      "transaction": "tx_failed",
      "operations": [
        "op_low_reserve"
      ]
    },
When the XLM balance equals to minimum required balance (thus it is impossible to submit any operation) the mistake is as follows
    "result_codes": {
      "transaction": "tx_insufficient_balance"
    },

**Comment by irisli** [comment]
Oh good point. Thanks!

**Comment by irisli** [comment]
https://github.com/irisli/stellarterm/pull/122

THanks
